# Generated by Django 4.1.6 on 2023-02-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='num_sts',
            field=models.IntegerField(verbose_name='Номер СТС'),
        ),
    ]
