# Generated by Django 4.1.6 on 2023-02-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_cars_num_sts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodels',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='manufacturers',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='mechanics',
            options={'verbose_name': 'Механик', 'verbose_name_plural': 'Механики'},
        ),
        migrations.AlterModelOptions(
            name='owners',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=2000, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.manufacturers', verbose_name='Производитель'),
        ),
    ]
