# Generated by Django 4.1.6 on 2023-02-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_carmodels_options_alter_manufacturers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='date_of_issue',
            field=models.DateField(blank=True, verbose_name='Дата окончания ремонта'),
        ),
    ]
