# Generated by Django 4.1.6 on 2023-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_cars_date_of_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_repair', models.CharField(max_length=150, verbose_name='Вид ремонтных работ')),
                ('price', models.IntegerField(verbose_name='Стоимость работы')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-лист',
            },
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='cars',
            name='type_of_repair',
        ),
        migrations.AddField(
            model_name='cars',
            name='type_of_repair',
            field=models.ManyToManyField(to='garage.pricelist', verbose_name='Вид ремонтных работ'),
        ),
    ]
