# Generated by Django 4.1.6 on 2023-02-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_alter_cars_date_of_issue_alter_cars_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturers',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Производитель'),
        ),
    ]
